spring:
  datasource:
      url: jdbc:mysql://localhost:3306/mydb
      username: root
      password: rootpassword
      driver-class-name: com.mysql.cj.jdbc.Driver

  mqtt:
    broker-url: tcp://localhost:1883
    client-id: spring-mqtt-client
    topic: my/topic
